name: Build-LaunchPad
on:
  workflow_dispatch: # запуск руками з вкладки Actions
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Restore NuGet
        run: nuget restore
      - name: Build Release
        run: msbuild /m /p:Configuration=Release
      - name: Upload DLLs
        uses: actions/upload-artifact@v4
        with:
          name: LaunchPad-Release
          path: |
            **/bin/Release/*.dll
            **/bin/Release/*.pdb
